dist: trusty
language: node_js
node_js:
  - '8'
  - '9'
  - '10'
  - '11'
cache:
  npm: false
branches:
  only:
  - master
before_install:
 - ./cleanup.sh
jobs:
  include:
    - stage: Building SDK
      script: npm run init
    - stage: Running Tests
      script: npm run test